services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data
    ports:
      - "27017:27017"
  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"      
  redis-insight:
    image: redislabs/redisinsight
    restart: unless-stopped
    ports:
      - "8080:8001"
volumes:
  redis-data:
  mongodb-data: